# -*- coding: utf-8 -*-
"""youtube_rag.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_Xccab6q9EY-TNb0UCmHaJm-0VGkK-vt
"""

import chromadb
import google.generativeai as genai

from youtube_transcript_api import YouTubeTranscriptApi
from langchain_text_splitters import RecursiveCharacterTextSplitter
from urllib.parse import urlparse, parse_qs

!pip install -q youtube-transcript-api

!pip install langchain

!pip install youtube_transcript_api
!pip install chromadb
!pip install sentence-transformers

from youtube_transcript_api import YouTubeTranscriptApi

video_id="90lLQVZe2Nc"
api = YouTubeTranscriptApi()
transcript=api.fetch(video_id)
text=" ".join([x.text for x in transcript])
print(text[:1000])

!pip install langchain_community
!pip install -U langchain-text-splitters

from langchain_text_splitters import RecursiveCharacterTextSplitter

splitter=RecursiveCharacterTextSplitter(
    chunk_size=500,
    chunk_overlap=100
)
chunks=splitter.split_text(text)
print("total chunks :", len(chunks))
print(chunks[0])

from sentence_transformers import SentenceTransformer
modell=SentenceTransformer('all-MiniLM-L6-v2')
embeddings=modell.encode(chunks)

print(embeddings.shape)

import chromadb

cc=chromadb.Client()
collection = cc.get_or_create_collection("youtube_rag")
for i,chunk in enumerate(chunks):
  collection.add(
      documents=[chunk],
      ids=[str(i)]
  )
  print("stored in chromaDB")

def retrieve(query, n_results=3):
    results = collection.query(
        query_texts=[query],
        n_results=n_results
    )

    return results['documents'][0]

!pip install -q google-generativeai

from google.colab import userdata

api_key = userdata.get('api_key')

import google.generativeai as genai

genai.configure(api_key="api_key")

model = genai.GenerativeModel("gemini-1.5-flash")

# !pip install -q -U google-generativeai

# from google.colab import userdata
# import google.generativeai as genai

# # Load API key
# api_key = userdata.get('api_key')

# # Configure Gemini
# genai.configure(api_key=api_key)

# # Load model
# model = genai.GenerativeModel("gemini-flash-lite-latest")
# # Test
# # response = model.generate_content("Explain RAG in simple terms")

# # print(response.text)

# for m in genai.list_models():
#     print(m.name)

query = "What does the speaker say about gratitude?"

retrieved_chunks = retrieve(query)

context = "\n".join(retrieved_chunks)

prompt = f"""
Answer ONLY from the context below.

Context:
{context}

Question:
{query}
"""

response = model.generate_content(prompt)

print(response.text)